# **Python Basics**

In [ ]:
1+2


3

In [ ]:
a=10
print(a+8)

18


Python is made for philosophy, to check the python **philosophy** write **"import this"**

In [ ]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [ ]:
print("Hello world")

Hello world


In [ ]:
print("welcome to python programming")

welcome to python programming


In [ ]:
# This is single line comment
'''
This is multi line commments
we can use triple quotes for
multi line comments
'''
print('Hello')

Hello


# **Variable Decleration**

In [ ]:
a=10
type(a)

int

In [ ]:
print(a)

10


In [ ]:
b = 'Rahim Ullah'
type(b)

str

In [ ]:
print(b)

Rahim Ullah


In [ ]:
##Integers
a=20
type(a)

int

In [ ]:
a+10

30

In [ ]:
a*10

200

In [ ]:
a%10

0

In [ ]:
print(type(a))

<class 'int'>


In [ ]:
a=92
b=25
print(a+b)

117


In [ ]:
#Floating
a=30.5
a

30.5

In [ ]:
print(type(a))

<class 'float'>


# **Type Casting**

In [ ]:
# float to integer
int(a)

30

# **Boolean**

In [ ]:
a1=True
b1=False

In [ ]:
type(a1)

bool

In [ ]:
print(type(b1))

<class 'bool'>


and/or operation on boolean variables

In [ ]:
a1 and b1

False

In [ ]:
a1 or b1

True

In [ ]:
# We can also and/or operation like this
a1 & b1

False

In [ ]:
a1 | b1

True

# **String**

In [ ]:
name1 = 'Rahim Ullah'
print(name1)
print(type(name1))

Rahim Ullah
<class 'str'>


In [ ]:
name1 + ' Zadran'

'Rahim Ullah Zadran'

In [ ]:
name1 + 1

TypeError: ignored

In [ ]:
name1 + str(1)

'Rahim Ullah1'

# **Complex Numbers**

In [ ]:
j=1.0-2.3j
j

(1-2.3j)

In [ ]:
print(j.real, j.imag)

1.0 -2.3


# Dynamic **Typing**

In [ ]:
a=10
a='Rahim Ullah'

# Strong **Typing**

In [ ]:
a='Rahim Ullah'
a+'2'

'Rahim Ullah2'

# String **Formatting**

In [ ]:
a=100
print('The value of a: ', a)

The value of a:  100


In [ ]:
first_name='Rahim Ullah'
last_name='Zadran'
print('The first name is {} and last name is {}'.format(first_name, last_name))

The first name is Rahim Ullah and last name is Zadran


In [ ]:
first_name='Rahim Ullah'
last_name='Zadran'
print('The first name is {1} and last name is {0}'.format(last_name,first_name))

The first name is Rahim Ullah and last name is Zadran


In [ ]:
first_name='Rahim Ullah'
last_name='Zadran'
print('The first name is {a} and last name is {b}'.format(b=last_name, a=first_name))

The first name is Rahim Ullah and last name is Zadran


# Input **Type**

In [ ]:
input('Enter the name ')

Enter the name Rahim Ullah


'Rahim Ullah'

In [ ]:
input('Enter the number ')

Enter the number 200


'200'

In [ ]:
a=input('Enter the value of a: ')
b=input('Enter the value of b: ')
print(a+b)

Enter the value of a: 20
Enter the value of b: 67
2067


In [ ]:
a=input('Enter the value of a: ')
b=input('Enter the value of b: ')
print(int(a)+int(b))

Enter the value of a: 30
Enter the value of b: 40
70


## **Control** **Flows**

In [ ]:
# if-statement
val = input('Enter the number ')
val_float=float(val)
print(val_float)
if(val_float>100):
  print('The value is greater than 100')

Enter the number 23
23.0


In [ ]:
# if-statement
val = input('Enter the number ')
val_float=float(val)
print(val_float)
if(val_float>100):
  print('The value is greater than 100')


Enter the number 299
299.0
The value is greater than 100


In [ ]:
# if-else statement
val = input('Enter the number ')
val_float=float(val)
if(val_float%2==0):
  print('The number is even')
else:
  print('The number is odd')

Enter the number 132
The number is even


In [ ]:
# Age form
# nested if-else condition

age= float(input('Enter your age: '))
if(age<18):
  print('Minor age')
elif(age>=18 and age<=35):
  print('Mid Age')
elif(age>=45 and age<=50):
  print('Senior mid age')
else:
  print('Senior citizen')

Enter your age: 46
Senior mid age


In [ ]:
# nested if-else condition

age= float(input('Enter your age: '))
if(age<18):
  print('Minor age')
  if(age<15):
    print('You are in School')
  else:
    print('You are in College')
elif(age>=18 and age<=35):
  print('Mid Age')
elif(age>=45 and age<=50):
  print('Senior mid age')
else:
  print('Senior citizen')

Enter your age: 16
Minor age
You are in College


# Loop Statement

In [ ]:
# for loop

lst=[1,2,3,4,5,6,7]
for i in lst:
  print(i)

1
2
3
4
5
6
7


In [ ]:
# for loop
# power

lst=[1,2,3,4,5,6,7]
for i in lst:
  print(i**2)

1
4
9
16
25
36
49


In [ ]:
# for loop
# find the sum of all elements in the list

lst=[1,2,3,4,5,6,7]
sum1 = 0
for i in lst:
  sum1=sum1+i

print(sum1)

28


In [ ]:
# find the sum of even and odd numbers

lst=[1,2,3,4,5,6,7]
even_sum = 0
odd_sum=0
for i in lst:
  if(i%2==0):
    even_sum=even_sum +i
  else:
    odd_sum = odd_sum+i

print('Even number sum is {} '.format(even_sum))
print('Odd number sum is {} '.format(odd_sum))

Even number sum is 12 
Odd number sum is 16 


In [ ]:
# while-condition

i=10
while(i<=10):
  print(i)
  i=i+1

10


In [ ]:
# break-statement

x=1
while(x<7):
  print(x)
  x=x+1

1
2
3
4
5
6


In [ ]:
# break-statement

x=1
while(x<7):
  print(x)
  if x==4:
    break
  x=x+1

1
2
3
4


In [ ]:
# break-statement

x=1
while(x<7):
  if x==4:
    print(x)
    break
  x=x+1

4


In [ ]:
# break-statement

x=1
while(x<7):
  if x==4:
    break
    print(x)

  x=x+1

In [ ]:
x = 1
while x < 7:
  if x == 4:
    print(x)
    x = x + 1
    continue

  x = x + 1


4


# Python Operators

*   Logical (not, and, or)
*   Equality
*   Comparision
*   Arithmetic





In [ ]:
type(False)

bool

In [ ]:
bool(1)

True

In [ ]:
a=True
b=False

In [ ]:
True and False

False

In [ ]:
True or False

True

In [ ]:
not True

False

In [ ]:
not False

True

In [ ]:
age = int(input('Ente the age '))

if age<18 or age>=35:
  print('Successful Execution')

Ente the age 16
Successful Execution


In [ ]:
# Equality-Operator

a='Rahim'
b='Rahim'

a==b

True

In [ ]:
# Equality-Operator

a='Rahim'
b='Rahim Ullah'

a==b

False

In [ ]:
age=int(input('Enter the age: '))

if age==18:
  print('You are in the teenager age')

Enter the age: 18
You are in the teenager age


In [ ]:
a= 'Rahim'
b= 'Rahim'
print(id(a))
print(id(b))

140626497574448
140626497574448


In [ ]:
# is checking memory location and == is checking the value
a is b

True

In [ ]:
lst = [1,2,3]
lst1 = [1,2,3]
print(id(lst))
print(id(lst1))

140626497450368
140626985430784


In [ ]:
lst is lst1

False

In [ ]:
lst is not lst1

True

In [ ]:
'Rahim' != 'Rahim'

False

In [ ]:
marks = float(input('Enter your marks '))

if marks>=35:
  print('Pass')
  if marks>=50 and marks<=70:
    print('First')
elif marks<35:
  print('Fail')

Enter your marks 59
Pass
First


# Arithmetic Operators


*   +
*   -
*   *
*   /    Division
*   //   Integer Division
*   %    Modulo Operator

In [ ]:
24+23


47

In [ ]:
32-4

28

In [ ]:
3*8

24

In [ ]:
10/2

5.0

In [ ]:
# // ignore the decimal like 9.6 and the answer will be 9
48//5

9

In [ ]:
48 % 5

3

# Python Number Methods

In [ ]:
1+2

3

##**Absolute number **:
In Python, the abs() function is a built-in function used to calculate the absolute value of a number. The absolute value of a number represents the distance of that number from zero on the number line, regardless of its positive or negative sign

In [ ]:
abs(-39)

39

In [ ]:
abs(23.40)

23.4

In [ ]:
abs(-53.04)

53.04

# Ceil()

 The ceil() function is a mathematical function available in the math module. It is used to round a given number up to the nearest integer greater than or equal to it. "Ceiling" refers to the concept of moving upward to the next whole number.

In [ ]:
import math
math.ceil(34.75)

35

In [ ]:
import math
math.ceil(34.2)

35

In [ ]:
math.ceil(-44.3)

-44

# Floor()

In [ ]:
math.floor(23.6)

23

In [ ]:
math.floor(46.3)

46

In [ ]:
math.floor(-30.4)

-31

# Exponential Value: exp()

exp() is a mathematical function provided by the math module that calculates the exponential value of a given number. The exp() function is used to compute the exponential function, where the input parameter represents the exponent.

In [ ]:
math.exp(10)

22026.465794806718

In [ ]:
math.exp(-8)

0.00033546262790251185

# fabs()

In [ ]:
math.fabs(10.53)

10.53

In [ ]:
math.fabs(-45.42)

45.42

# Log(x)

In [ ]:
math.log(20)

2.995732273553991

In [ ]:
math.log(65.4)

4.180522258463153

In [ ]:
math.log10(34)

1.5314789170422551

# Max()

In [ ]:
max(23,4,56,77,43,122,44,66,)

122

In [ ]:
max(-34,-55,-23,-45)

-23

## Min()

In [ ]:
min(45,6,33,67,7,88,55,34)

6

In [ ]:
min(-55,-77,-3,-66)

-77

# pow()

In [ ]:
import math
math.pow(3,2)

9.0

# sqrt()

In [ ]:
math.sqrt(16)

4.0

# Triggnometric function

In [ ]:
import math
math.sin(90)

0.8939966636005579

In [ ]:
math.sin(0)

0.0

In [ ]:
math.cos(90)

-0.4480736161291701

In [ ]:
math.tan(60)

0.320040389379563

In [ ]:
# hypot()

math.hypot(2,4)

4.47213595499958

# List

In Python, a list is a built-in data structure that represents a collection of elements. It is an ordered, mutable, and heterogeneous sequence, which means it can store elements of different types and allows for modification of its contents.

Lists are defined using square brackets [ ] and can contain zero or more elements separated by commas. Here's an example of a list:

In [ ]:
# So first lets understand mutuable and immutable
# String are immutuble and List is mutuble

str1 = 'Rahim Ullah'
str

str

In [ ]:
str1[3]

'i'

In [ ]:
# String are immutable, we cannot change the character of a string
str[3]='e'

TypeError: ignored

In [ ]:
# List
type([])

list

In [ ]:
lst = [1,2,3,'Rahim', 'Python',6,4,'Java']
print(lst)
print(lst[0])
lst[3]

[1, 2, 3, 'Rahim', 'Python', 6, 4, 'Java']
1


'Rahim'

In [ ]:
# mutuable
lst = [1,2,3,'Rahim', 'Python',6,4,'Java']
lst[4]='C++'
print(lst[4])
print(lst)

C++
[1, 2, 3, 'Rahim', 'C++', 6, 4, 'Java']


In [ ]:
# converting
lst = list((2,4,5,6,7,'python'))
print(lst)
print(type(lst))

[2, 4, 5, 6, 7, 'python']
<class 'list'>


In [ ]:
lst = [2,3,7,8,3,4]
for i in lst:
  print(i)

2
3
7
8
3
4


In [ ]:
lst = [2,3,7,8,3,4]
for i in lst:
  print(i**2)

4
9
49
64
9
16


In [ ]:
# inbuilt functions in list

len(lst)

6

In [ ]:
max(lst)

8

In [ ]:
min(lst)

2

Append function in list

In [ ]:
lst = [2,4,5,6,7,8]
print(lst)

[2, 4, 5, 6, 7, 8]


In [ ]:
lst.append(29)
print(lst)

[2, 4, 5, 6, 7, 8, 29]


In [ ]:
lst.append(['Rahim Ullah', 'Zadran'])
print(lst)

[2, 4, 5, 6, 7, 8, 29, ['Rahim Ullah', 'Zadran']]


In [ ]:
lst[7]

['Rahim Ullah', 'Zadran']

In [ ]:
lst[7][1]

'Zadran'

In [ ]:
#Accessing the elements of a list
lst = [1,2,3,4,4,5,6,77,9]
lst[:]

[1, 2, 3, 4, 4, 5, 6, 77, 9]

In [ ]:
lst[:4]

[1, 2, 3, 4]

In [ ]:
lst[3:]

[4, 4, 5, 6, 77, 9]

In [ ]:
lst[2:6]

[3, 4, 4, 5]

Insert function

In [ ]:
# insert in a specific order

lst.insert(2, 'Python')
lst

[1, 2, 'Python', 3, 4, 4, 5, 6, 77, 9]

Extend function

In [ ]:
# extend method will add the multiple items at the end of the list

lst.extend([88,22, 'Java'])
lst

[1, 2, 'Python', 3, 4, 4, 5, 6, 77, 9, 88, 22, 'Java']

Various operations that we can perform on list

In [ ]:
lst = [2,4,5,8,9]
sum(lst)

28

In [ ]:
# It will append 4 times
lst*4

[2, 4, 5, 8, 9, 2, 4, 5, 8, 9, 2, 4, 5, 8, 9, 2, 4, 5, 8, 9]

Pop() method

In [ ]:
lst = [2,3,4,5,6,7]
print(lst)
print(lst.pop())
print(lst)
print(lst.pop(3))
print(lst)

[2, 3, 4, 5, 6, 7]
7
[2, 3, 4, 5, 6]
5
[2, 3, 4, 6]


Count()

In [ ]:
lst = [2,3,4,5,6,2,2,6,7]
lst.count(2)

3

Remove function

In [ ]:
lst = [2,3,4,5,6]
lst.remove(4)
lst

[2, 3, 5, 6]

# Sets
In Python, a set is an unordered collection of unique elements. It is a built-in data type that is used to store a collection of distinct items. Sets are mutable, meaning you can add or remove elements from them. And set has no duplicate elements. The elements of set are commonly enclosed in curly braces { } .

In [ ]:
# if the set is empty it will consider the dictionary
type({})

dict

In [ ]:
type({2,4,5,6,7,3,'Rahim'})

set

In [ ]:
set1 = set([2,3,4,5,6,7,8,8])
print(set1)
print(type(set1))

{2, 3, 4, 5, 6, 7, 8}
<class 'set'>


In [ ]:
set1 = {2,3,45,6,7}
set1

{2, 3, 6, 7, 45}

In [ ]:
set1 = {'Rahim', 'Zadran', 2,5,7,8}

for i in set1:
  print(i)

2
Zadran
5
7
8
Rahim


In [ ]:
# Add value to the set

set1 = {'Rahim', 'Zadran', 'Python', 'Java'}
set1.add('C++')
set1

{'C++', 'Java', 'Python', 'Rahim', 'Zadran'}

In [ ]:
# set intersection

set1 = {2,3,5,6,7,8}
set2 = {4,5,8,9,0,1}
set2.intersection(set1)

{5, 8}

In [ ]:
# difference function

set1 = {2,3,5,6,7,8}
set2 = {4,5,8,9,0,1}
set1.difference(set2)

{2, 3, 6, 7}

In [ ]:
# union function

set1 = {2,3,5,6,7,8}
set2 = {4,5,8,9,0,1}

set1.union(set2)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

# Dictionaries

In Python, a dictionary is a built-in data structure that stores a collection of key-value pairs. It is also known as an associative array or hash map in other programming languages. Dictionaries are mutable, unordered, and allow for fast access to values based on their keys.

In [ ]:
type({})

dict

In [ ]:
type({1})

set

In [ ]:
# key-value pair

type({1:'Rahim Ullah'})

dict

In [ ]:
dict(name='Rahim', age= '26', sur_name='Zadran')

{'name': 'Rahim', 'age': '26', 'sur_name': 'Zadran'}

In [ ]:
my_dict = {
    'car1' :'Audi',
    'car2' :'BMW',
    'car3' :'Toyota'
}
my_dict['car1']

'Audi'

In [ ]:
my_dict.items()

dict_items([('car1', 'Audi'), ('car2', 'BMW'), ('car3', 'Toyota')])

In [ ]:
my_dict.keys()

dict_keys(['car1', 'car2', 'car3'])

In [ ]:
my_dict.values()

dict_values(['Audi', 'BMW', 'Toyota'])

In [ ]:
my_dict['car4']='MG'
my_dict

{'car1': 'Audi', 'car2': 'BMW', 'car3': 'Toyota', 'car4': 'MG'}

Nested Dictionaries

In [ ]:
car1_model={'Mercedes':1960}
car2_model={'Audi':2000}
car3_model={'BMW':2020}

car_type = {'car1':car1_model, 'car2':car2_model, 'car3':car3_model}

print(car_type)

{'car1': {'Mercedes': 1960}, 'car2': {'Audi': 2000}, 'car3': {'BMW': 2020}}


In [ ]:
car_type['car2']

{'Audi': 2000}

In [ ]:
car_type['car2']['Audi']

2000

# Tuples
In Python, a tuple is an ordered, immutable collection of elements enclosed in parentheses (). Tuples are similar to lists, but the key difference is that tuples are immutable, meaning their elements cannot be modified once they are assigned. This immutability makes tuples useful for representing fixed collections of items that should not be changed.

In [ ]:
# create an empty tuple
my_tuple = tuple()
type(my_tuple)

tuple

In [ ]:
my_tuple = ('Python','Java','C++')
my_tuple

('Python', 'Java', 'C++')

In [ ]:
my_tuple[0]

'Python'

In [ ]:
my_tuple.index('Java')

1

# Representation of List, Set, Dictionary, Tuples

*   List [ ]
*   Set { } or {1,2,3}
*   Dict {key : value}
*   Tuple ( )







# Numpy

Numpy is general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with python.

# What is an Array
A NumPy array, short for Numerical Python array, is a fundamental data structure in Python's NumPy library. It represents a grid of values, either in a single dimension (1-D array), two dimensions (2-D array), or multi-dimensions (n-D array). It is similar to a list but provides more efficient storage and operations for numerical computations.

In [ ]:
# import the library
import numpy as np

lst = [1,2,3,4,5]
arr = np.array(lst)
type(arr)

numpy.ndarray

In [ ]:
arr.shape

(5,)

In [ ]:
lst1 = [1,2,3,4,5]
lst2 = [6,7,8,9,1]
lst3 = [4,5,6,7,8]

arr1 = np.array([lst1, lst2, lst3])
arr1

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [4, 5, 6, 7, 8]])

In [ ]:
arr1.shape

(3, 5)

In [ ]:
# indexing
arr[2]

3

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[2]=10
arr

array([ 1,  2, 10,  4,  5])

In [ ]:
arr[1:4]

array([ 2, 10,  4])

In [ ]:
arr[-1]

5

In [ ]:
arr[:-1]

array([ 1,  2, 10,  4])

In [ ]:
arr[::]

array([ 1,  2, 10,  4,  5])

In [ ]:
arr[::-2]

array([ 5, 10,  1])

In [ ]:
arr1

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [4, 5, 6, 7, 8]])

In [ ]:
arr1[:,1]

array([2, 7, 5])

In [ ]:
arr1[1:2,1:2]

array([[7]])

In [ ]:
arr1[1:, 1:3]

array([[7, 8],
       [5, 6]])

In [ ]:
print(arr1[1][1])
print(arr1[2][4])

7
8


In [ ]:
# EDA Point of view
arr

array([ 1,  2, 10,  4,  5])

In [ ]:
arr<3

array([ True,  True, False, False, False])

In [ ]:
arr[arr<3]

array([1, 2])

In [ ]:
arr1

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [4, 5, 6, 7, 8]])

In [ ]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 4, 5],
       [6, 7, 8]])

In [ ]:
# mechanism to create an array

arr3 = np.arange(1,10,1)
arr4 = np.arange(1,10,2)
print(arr3)
print(arr4)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [ ]:
arr3 = np.arange(1,20,2).reshape(2,5)
arr3

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [ ]:
arr

array([ 1,  2, 10,  4,  5])

In [ ]:
arr*arr

array([  1,   4, 100,  16,  25])

In [ ]:
arr*2

array([ 2,  4, 20,  8, 10])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.random.randint(20,40)

33

In [ ]:
np.random.randint(20,40,4)

array([20, 23, 22, 23])

In [ ]:
np.random.randint(20,40,4).reshape(2,2)

array([[24, 26],
       [28, 28]])

# Pandas

In this part we are going to learn about


1.   Pandas Dataframe
2.   Pandas Series
3.   Pandas Basic Operation



In [ ]:
import pandas as pd
import numpy as np


In [ ]:
arr = np.arange(0,20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
df = pd.DataFrame(arr, index=['Row1', 'Row2', 'Row3', 'Row4', 'Row4'], columns=['Column1', 'Column2', 'Column3', 'Column4'])
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row4       16       17       18       19

In [ ]:
df.head(2)

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [ ]:
df.tail(2)

Column1  Column2  Column3  Column4
Row4       12       13       14       15
Row4       16       17       18       19

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes


In [ ]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [ ]:
# indexing
# Two ways of indexing columnname and rowindex[loc], rowindex columnindex number[.iloc]

In [ ]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row4       16       17       18       19

In [ ]:
# By using columnname
df['Column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row4    16
Name: Column1, dtype: int64

In [ ]:
# Series = either row or column
# Combinig multiple rows or columns then it is called dataframe
type(df['Column1'])

pandas.core.series.Series

In [ ]:
# By using columnname

df[['Column1', 'Column2']]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row4       16       17

In [ ]:
# by using row index name
df.loc['Row3']

Column1     8
Column2     9
Column3    10
Column4    11
Name: Row3, dtype: int64

In [ ]:
type(df.loc['Row3'])

pandas.core.series.Series

In [ ]:
# by using row index name
df.loc[['Row3', 'Row4']]

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15
Row4       16       17       18       19

In [ ]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row4       16       17       18       19

In [ ]:
# by using indexing techniques
df.iloc[2:4,0:2]

Column1  Column2
Row3        8        9
Row4       12       13

In [ ]:
df.iloc[2:, 1:]

Column2  Column3  Column4
Row3        9       10       11
Row4       13       14       15
Row4       17       18       19

In [ ]:
df.iloc[2:4,3:4]

Column4
Row3       11
Row4       15

In [ ]:
# convert dataframe into arrays

df.iloc[2:, 1:].values

array([[ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [ ]:
## Basic Operations
df.isnull()

Column1  Column2  Column3  Column4
Row1    False    False    False    False
Row2    False    False    False    False
Row3    False    False    False    False
Row4    False    False    False    False
Row4    False    False    False    False

In [ ]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [ ]:
df = pd.DataFrame(data=[[1, np.nan, 2],[1,3,4]], index=['Row1', 'Row2'], columns=['Column1', 'Column2', 'Column3'])
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [ ]:
# check the null value
df.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False

In [ ]:
df.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [ ]:
df.head()

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [ ]:
df['Column3'].value_counts()

2    1
4    1
Name: Column3, dtype: int64

In [ ]:
df['Column3'].unique()

array([2, 4])

In [ ]:
df = pd.DataFrame(arr, index=['Row1', 'Row2', 'Row3', 'Row4', 'Row4'], columns=['Column1', 'Column2', 'Column3', 'Column4'])
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row4       16       17       18       19

In [ ]:
df>2

Column1  Column2  Column3  Column4
Row1    False    False    False     True
Row2     True     True     True     True
Row3     True     True     True     True
Row4     True     True     True     True
Row4     True     True     True     True

In [ ]:
df[df['Column2']>2]

Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row4       16       17       18       19

# Pandas Part-2
In this part we will learn about


1.   StringIO
2.   Pandas read_csv



In [ ]:
# Reading different data sources with help of pandas

from io import StringIO

In [ ]:
import pandas as pd
df=pd.read_csv('mercedesbenz.csv')
df

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 378 columns]

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
data=('col1, col2, col3\n'
'x, y, 1\n'
'a, b, 2\n'
'c, d, 3'
)

In [ ]:
type(data)

str

In [ ]:
# in memory file format
StringIO(data)

In [ ]:
pd.read_csv(StringIO(data))

col1  col2   col3
0    x     y      1
1    a     b      2
2    c     d      3

In [ ]:
import pandas as pd
df=pd.read_csv('mercedesbenz.csv', usecols=['X1', 'X2', 'X3', 'X4', 'X5'])
df.head()

X1  X2 X3 X4 X5
0  v  at  a  d  u
1  t  av  e  d  y
2  w   n  c  d  x
3  t   n  f  d  x
4  v   n  f  d  h

In [ ]:
df1=df.to_csv('test.csv', index=False)

In [ ]:
data=('a, b, c, d\n'
'1,2,3,4\n'
'5,6,7,8\n'
'3,4,9'
)

In [ ]:
df=pd.read_csv(StringIO(data))
df

a   b   c    d
0  1   2   3  4.0
1  5   6   7  8.0
2  3   4   9  NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       3 non-null      int64  
 1    b      3 non-null      int64  
 2    c      3 non-null      int64  
 3    d      2 non-null      float64
dtypes: float64(1), int64(3)
memory usage: 224.0 bytes


In [ ]:
df=pd.read_csv(StringIO(data), dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   a       3 non-null      object
 1    b      3 non-null      object
 2    c      3 non-null      object
 3    d      2 non-null      object
dtypes: object(4)
memory usage: 224.0+ bytes


In [ ]:
df.head()

a  b  c    d
0  1  2  3    4
1  5  6  7    8
2  3  4  9  NaN

In [ ]:
df.isnull().sum()

a     0
 b    0
 c    0
 d    1
dtype: int64

In [ ]:
# indexing

df['a'][0]

'1'

In [ ]:
df.dtypes

a     object
 b    object
 c    object
 d    object
dtype: object

## Day 11
## Pyton Pandas working with JSON
In this part we are going to learn about


*   read json (read_json)
*   to json (to_json)
*   Json Normalize






In [ ]:
data = '{"employe_name": "James", "email": "james@gmail.com", "job_profile":[{"title":"Team Lead", "title":"Sr", "Position": "Data Scientist"}]}'

In [ ]:
type(data)

str

In [ ]:
import pandas as pd

In [ ]:
pd.read_json(data)

employe_name            email                                    job_profile
0        James  james@gmail.com  {'title': 'Sr', 'Position': 'Data Scientist'}

In [ ]:
pd.read_json(data, orient='record')

employe_name            email                                    job_profile
0        James  james@gmail.com  {'title': 'Sr', 'Position': 'Data Scientist'}

In [ ]:
pd.read_json(data, orient='index')

0
employe_name                                            James
email                                         james@gmail.com
job_profile   [{'title': 'Sr', 'Position': 'Data Scientist'}]

In [ ]:
pd.read_json(data, orient='column')

employe_name            email                                    job_profile
0        James  james@gmail.com  {'title': 'Sr', 'Position': 'Data Scientist'}

In [ ]:
import pandas as pd
df = pd.DataFrame([['a','b'],['c','d']],
                   index = ['row1', 'row2'],
                   columns = ['col 1', 'col 2']
                   )

In [ ]:
df

col 1 col 2
row1     a     b
row2     c     d

In [ ]:
df.to_json(orient = 'index')

'{"row1":{"col 1":"a","col 2":"b"},"row2":{"col 1":"c","col 2":"d"}}'

In [ ]:
df.to_json(orient = 'columns')

'{"col 1":{"row1":"a","row2":"c"},"col 2":{"row1":"b","row2":"d"}}'

In [ ]:
df.to_json(orient = 'records')

'[{"col 1":"a","col 2":"b"},{"col 1":"c","col 2":"d"}]'

In [ ]:
df.to_json(orient = 'split')

'{"columns":["col 1","col 2"],"index":["row1","row2"],"data":[["a","b"],["c","d"]]}'

In [ ]:
df.to_json(orient = 'table')

'{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col 1","type":"string"},{"name":"col 2","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"row1","col 1":"a","col 2":"b"},{"index":"row2","col 1":"c","col 2":"d"}]}'

In [ ]:
data = [{"employe_name": "James", "email": "james@gmail.com", "job_profile":{"title":"Team Lead", "title":"Sr", "Position": "Data Scientist"}}]

In [ ]:
data

[{'employe_name': 'James',
  'email': 'james@gmail.com',
  'job_profile': {'title': 'Sr', 'Position': 'Data Scientist'}}]

In [ ]:
pd.json_normalize(data)

employe_name            email job_profile.title job_profile.Position
0        James  james@gmail.com                Sr       Data Scientist

# Day 12: Python Pandas working with HTML Tutorial
In this part we are going to learn about


1.   read HTML(read_html)
2.   to HTML(to_html)



In [ ]:
import pandas as pd

In [ ]:
html = pd.read_html("https://en.wikipedia.org/wiki/Mobile_country_code")

In [ ]:
type(html)

list

In [ ]:
html

[   MCC  MNC Brand      Operator       Status Bands (MHz)  \
 0    1    1  TEST  Test network  Operational         any   
 1    1    1  TEST  Test network  Operational         any   
 2  999   99   NaN  Internal use  Operational         any   
 3  999  999   NaN  Internal use  Operational         any   
 
                               References and notes  
 0                                              NaN  
 1                                              NaN  
 2  Internal use in private networks, no roaming[4]  
 3  Internal use in private networks, no roaming[4]  ,
      Mobile country code                                    Country ISO 3166  \
 0                    289                                 A Abkhazia    GE-AB   
 1                    412                                Afghanistan       AF   
 2                    276                                    Albania       AL   
 3                    603                                    Algeria       DZ   
 4               

In [ ]:
html[0]

MCC  MNC Brand      Operator       Status Bands (MHz)  \
0    1    1  TEST  Test network  Operational         any   
1    1    1  TEST  Test network  Operational         any   
2  999   99   NaN  Internal use  Operational         any   
3  999  999   NaN  Internal use  Operational         any   

                              References and notes  
0                                              NaN  
1                                              NaN  
2  Internal use in private networks, no roaming[4]  
3  Internal use in private networks, no roaming[4]

In [ ]:
html[1]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]

In [ ]:
html[3]

MCC  MNC     Brand                 Operator       Status Bands (MHz)  \
0  995    1  FonePlus  Sure (Diego Garcia) Ltd  Operational     GSM 900   

                                References and notes  
0  There appears to be no officially assigned MCC...

# New York City
https://en.wikipedia.org/wiki/New_York_City

In [ ]:
html = pd.read_html("https://en.wikipedia.org/wiki/Mobile_country_code")

In [ ]:
html[0]

MCC  MNC Brand      Operator       Status Bands (MHz)  \
0    1    1  TEST  Test network  Operational         any   
1    1    1  TEST  Test network  Operational         any   
2  999   99   NaN  Internal use  Operational         any   
3  999  999   NaN  Internal use  Operational         any   

                              References and notes  
0                                              NaN  
1                                              NaN  
2  Internal use in private networks, no roaming[4]  
3  Internal use in private networks, no roaming[4]

In [ ]:
html[0]['MCC']

0      1
1      1
2    999
3    999
Name: MCC, dtype: int64

In [ ]:
html = pd.read_html("https://en.wikipedia.org/wiki/Mobile_country_code")

In [ ]:
html[0]

MCC  MNC Brand      Operator       Status Bands (MHz)  \
0    1    1  TEST  Test network  Operational         any   
1    1    1  TEST  Test network  Operational         any   
2  999   99   NaN  Internal use  Operational         any   
3  999  999   NaN  Internal use  Operational         any   

                              References and notes  
0                                              NaN  
1                                              NaN  
2  Internal use in private networks, no roaming[4]  
3  Internal use in private networks, no roaming[4]

In [ ]:
type(html[0])

pandas.core.frame.DataFrame

# Day 13- Python Pandas Working With XML Tutorials- Part 5
Read XML and get Dataframe
Convert Dataframe to XML
What is XML?

*   XML stands for eXtensible Markup Language
*   XML is a markup language much like HTML
*   XML was designed to store and transport data
*   XML was designed to be self-descriptive
*   XML is a W3C Recommendation

In [ ]:
html[0].to_html('demo.html')

In [ ]:
import pandas as pd

In [ ]:
xml ='''<?xml version="1.0" encoding="UTF-8"?>
<root>
 <node>
  <element1>Stefan</element1>
  <element2>42</element2>
  <element3>Shirt</element3>
  <element4>3000</element4>
</node>
<node>
  <element1>Stedd</element1>
  <element2>477</element2>
  <element4>3430</element4>
</node>
<node>
  <element1>Stefan</element1>
  <element2>66</element2>
  <element3>Shirt</element3>
  <element4>5500</element4>
</node>
</root>'''


In [ ]:
pd.read_xml(xml)

element1  element2 element3  element4
0   Stefan        42    Shirt      3000
1    Stedd       477     None      3430
2   Stefan        66    Shirt      5500

# Function in Python
Why use function:


1.   To make code more readable
2.   To make code more efficient
3.   To make code more maintainable
4.   To make code more reusable
5.   To make code more extensible



In [ ]:
def welcome():
  print('Welcome to Pythong programming...')

welcome()
welcome()
welcome()

Welcome to Pythong programming...
Welcome to Pythong programming...
Welcome to Pythong programming...


In [ ]:
def welcome()->str:
  return 'Welcome to Pythong programming'

print(welcome())
welcome()
welcome()

Welcome to Pythong programming


'Welcome to Pythong programming'

In [ ]:
def welcome()->str:
  """
  Description: This function will show a welcome message

  Return: This function will return the welcome message
  """
  return 'Welcome to Pythong programming'

msg = welcome()
print(msg)

Welcome to Pythong programming


In [ ]:
def welcome(msg):
  return msg

x = welcome('Hi Rahim Ullah')
y= welcome('This is programming')
print(x + '\n' + y)


Hi Rahim Ullah
This is programming


Function to Add even and odd number:

In [ ]:
def even_odd_sum(lst):
  even_sum = 0
  odd_sum = 0
  for i in lst:
    if i % 2 == 0:
      even_sum += i
    else:
      odd_sum += i

  return even_sum, odd_sum

sum1, sum2 = even_odd_sum([1,3,4,5,6,6,7,8,8,8,6,554,3,23,2,234,5,55,52])
print(sum1, sum2)


888 102


# Introduction To OOPS, Classes, Constructors,Methods
class consist of methods and attributes



In [ ]:
class Car:
  def __init__(self, window, tyres, engine):
    self.window = window
    self.tyres = tyres
    self.engine = engine

  def self_driving(self):
    print('The car has a {} engine'.format(self.engine))

car1 = Car(4, 4, 'petrol')
print('The number of tyres in object car1 is {}'.format(car1.tyres))
print('The number of windows in object car1 is {}'.format(car1.window))

car1.self_driving()


The number of tyres in object car1 is 4
The number of windows in object car1 is 4
The car has a petrol engine


# Multiple Constructors In Python
Python does not support multiple constructors, belwo is the example, we cannot execute the first constructor otherwise it will automatically call the second constructor.

In [ ]:
class Animal:
  def __init__(self, name, species):
    self.name = name
    self.species = species

  def __init__(self, name, species, age):
    self.name = name
    self.species = species
    self.age = age

  def makeSound(self, sound):
    return "The animal is {} and says {}".format(self.name, sound)

dog = Animal("dog","mamal", 22)
print(dog)

# Multiple Constructor with help of Positional keyword Arguements:
We can write and execute multiple constructor through positional keyword arguments. and also by using multiple ***if-else statment*** in the constructor

In [ ]:
class Animal:
  def __init__(self, *args):
    if len(args)==1:
      self.name = args[0]
    elif len(args)==2:
      self.name = args[0]
      self.species = args[1]
    elif len(args)==3:
      self.name = args[0]
      self.species = args[1]
      self.age = args[2]
  def makeSound(self, sound):
    return "The animal is {} and says {}".format(self.name, sound)

dog = Animal("dog", "mammals", 17)
print(dog.name)
print(dog.species)
print(dog.age)
print(dog.makeSound("woof woof"))

dog
mammals
17
The animal is dog and says woof woof


# Inheritance

In [ ]:
class Car:
  def __init__(self, windows, door, enginetype):
    self.windows = windows
    self.door = door
    self.enginetype = enginetype

  def driving(self):
    print('Car is used for driving')

# Audi Car is inheriting Car class.
class Audi(Car):
  def __init__(self, windows, door, enginetype, horsepower):
    super().__init__(windows, door, enginetype)
    self.horsepower = horsepower

  def selfdriving(self):
    print('audic7 is a self-driving car')

# Object
audic7 = Audi(4, 6, "Diesel", 200)
print(audic7.horsepower)
print(audic7.windows)
audic7.driving()
audic7.selfdriving()


car1 = Car(4, 2, "Petrol")
print(car1)
print(car)

200
4
Car is used for driving
audic7 is a self-driving car


In [ ]:
print(car1.windows)

4


In [ ]:
print(dir(audic7))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'door', 'driving', 'enginetype', 'horsepower', 'selfdriving', 'windows']


In [ ]:
print(dir(car1))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'door', 'driving', 'enginetype', 'windows']


# Python List Comprehension

In [ ]:
type([2,4,5,6,8,1])

list

In [ ]:
lst = []
for i in range(0,8):
  lst.append(i)

print(lst)

[0, 1, 2, 3, 4, 5, 6, 7]


In [ ]:
lst = [1,2,3,4,5,6]
lst2 = []

for i in lst:
  lst2.append(i**2)

print(lst2)

[1, 4, 9, 16, 25, 36]


In [ ]:
numbers = [1,2,3,4,5]
squared_numbers = [i**2 for i in numbers]
print(squared_numbers)

[1, 4, 9, 16, 25]


In [ ]:
#filtering even numbers from a list

numbers = [1,2,3,4,5,6,7,8,9,10]
even_number = [n for n in numbers if n%2==0]
print(even_number)

[2, 4, 6, 8, 10]


In [ ]:
#Flatterning a list of lists: 2 for loops
lists = [[1,2,3],[4,5,6],[7,8,9]]
flattend_list = [item for sublist in lists for item in sublist]
print(flattend_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
#Generating a list of the first letters of words in a list:
words = ["apple", "banana", "mangoes", "waterMelon"]
first_letters = [word[0] for word in words]
print(first_letters)

['a', 'b', 'm', 'w']


In [ ]:
#Generating a list of the squares of even numbers
numbers = [1,2,3,4,5,6,7,8,9,10]
print([n for n in numbers if n%2==0]) #even number
print([n**2 for n in numbers if n%2==0]) # square of even number

[2, 4, 6, 8, 10]
[4, 16, 36, 64, 100]


In [ ]:
# Converting a list of strings into a list of integers
strings = ['1','2','3','4','5']
[int(i) for i in strings]

[1, 2, 3, 4, 5]

In [ ]:
fib = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765]
[fib[i-1]+fib[i-2] for i in range(2, len(fib))]

[1,
 2,
 3,
 5,
 8,
 13,
 21,
 34,
 55,
 89,
 144,
 233,
 377,
 610,
 987,
 1597,
 2584,
 4181,
 6765]

In [ ]:
##Generating a list of all the divisors of a number:
number = 36
[i for i in range(1, number+1) if number%i==0]

[1, 2, 3, 4, 6, 9, 12, 18, 36]

#Lambda Function In Python
 In Python, a lambda function (also called an anonymous function) is a small, anonymous function that can be defined in a single line of code without a name. It is useful when we need a simple function that we don't want to define explicitly using the def keyword. The basic syntax for a lambda function in Python is:

lambda arguments: expression
Here, arguments refer to the input arguments for the function and expression is a single expression that gets evaluated and returned as the result of the function. The result of the expression is automatically returned by the lambda function, so there's no need to use the return statement.

In [ ]:
# Addition
f = lambda x, y: x+y
f

<function __main__.<lambda>(x, y)>

In [ ]:
f(10,34)

44

In [ ]:
# Multiplication
add = lambda x,y: x*y
add(10,5)

50

In [ ]:
# Return length of a string
string_length = lambda s:len(s)
string_length("Rahim Ullah")

11

In [ ]:
# Converting a list of integers to their corrospending square values:
numbers = [1,2,3,4,5,6]
squares = list(map(lambda x:x**2, numbers))
print(squares)

[1, 4, 9, 16, 25, 36]


In [ ]:
# Filter out even number from a list
numbers = [1,2,3,4,5,6]
list(filter(lambda x:x%2==0, numbers))

[2, 4, 6]

In [ ]:
f = lambda x:x%2==0
f(3)

False

In [ ]:
f(4)

True

In [ ]:
# sort a list of string based on alphabitical character and length:
fruits = ['apple', 'mango', 'date', 'banana']
sorted(fruits, key=lambda x:len(x))

['date', 'apple', 'mango', 'banana']

In [ ]:
sorted(fruits)

['apple', 'banana', 'date', 'mango']

In [ ]:
# complex example
# Sorting a list of dictionaries based on a specific key

people = [
    {'name': 'Alice', 'age': 25, 'occupation': 'Engineer'},
    {'name': 'Bob', 'age': 30, 'occupation': 'Manager'},
    {'name': 'Charlie', 'age': 22, 'occupation': 'Intern'},
    {'name': 'Dave', 'age': 27, 'occupation': 'Designer'},
]

In [ ]:
sorted(people, key=lambda x:x['age'])

[{'name': 'Charlie', 'age': 22, 'occupation': 'Intern'},
 {'name': 'Alice', 'age': 25, 'occupation': 'Engineer'},
 {'name': 'Dave', 'age': 27, 'occupation': 'Designer'},
 {'name': 'Bob', 'age': 30, 'occupation': 'Manager'}]

In [ ]:
sorted(people, key=lambda x:(x['age'], x['age']))

[{'name': 'Charlie', 'age': 22, 'occupation': 'Intern'},
 {'name': 'Alice', 'age': 25, 'occupation': 'Engineer'},
 {'name': 'Dave', 'age': 27, 'occupation': 'Designer'},
 {'name': 'Bob', 'age': 30, 'occupation': 'Manager'}]

In [ ]:
# Finding the maximum value in a dictionary
data = {'a':10, 'b':20, 'c':5, 'd':15}
max(data, key= lambda x:data[x])

'b'

In [ ]:
## Grouping a list of strings based on their first letter
from itertools import groupby

words = ['apple', 'banana', 'cherry', 'date', 'elderberry', 'fig']

groups = groupby(sorted(words), key=lambda x: x[0])

for key, group in groups:
    print(key, list(group))

a ['apple']
b ['banana']
c ['cherry']
d ['date']
e ['elderberry']
f ['fig']
